### ISSUE TITLE
I can't find any example for dcp client.

### ISSUE THREAD

**Issue by azvast** [Distributed-Compute-Labs/dcp-client#14]
How can I make a dcp client for only worker?

Now all current codes include compute.for, but I don't want to include it in my code for only working in node.js

https://github.com/doriansmiley/dcp-worker/blob/main/index.js
Above code seems similar, but not working.

**Comment by YarnSaw** [comment]
Are you looking to create a new version of a webpacked bundle that only includes the code required for a worker, or to use the worker code that exists within the bundle?

A repo with a working version of the worker is https://github.com/Distributed-Compute-Labs/dcp-worker. Check out `bin/dcp-worker` for the script that starts a worker. Documentation for the worker exists at https://docs.dcp.dev/specs/worker-api.html. 

To use the worker, an evaluator is also required - the secure environment the work functions from jobs can run in. You can download a windows MSI for it at [https://updates.kingsds.network/downloads/latest/omaha/DCP%20Worker/win/stable/](https://updates.kingsds.network/downloads/latest/omaha/DCP%20Worker/win/stable/)

If you start the evaluator (the dcp-worker repo also has a script to help with that), you can start the worker, and it should run.

**Comment by azvast** [comment]
Thanks for your help!
